Repository codestates-seb/seb40_main_037, pull requests merged in 2022-11, with the labels that each got.

#9 :sparkles: feat: Footer 구현
  client/public/logo.png
  client/src/App.jsx
  client/src/components/Footer/index.jsx
  client/src/components/Footer/style.js
  client/src/components/Header/index.jsx
  client/src/components/Header/style.js
  client/src/components/Layout/style.js
  client/src/constants/footer.js
  client/src/pages/Main.jsx
  client/src/styles/globalStyle.js
  client/src/styles/index.js
  client/src/styles/theme.js
Labels: ✨기능추가, 🌈레이아웃, 🧑‍💻Front

#11 feat: Audit,Dto config,Exception,Page Class 생성
  .idea/compiler.xml
  .idea/dbnavigator.xml
  .idea/gradle.xml
  server/src/main/java/server/beerfactory/audit/Auditable.java
  server/src/main/java/server/beerfactory/dto/config/MultiResponseDto.java
  server/src/main/java/server/beerfactory/dto/config/PageInfo.java
  server/src/main/java/server/beerfactory/dto/config/SingleResponseDto.java
  server/src/main/java/server/beerfactory/exception/BusinessLogicException.java
  server/src/main/java/server/beerfactory/exception/ExceptionCode.java
Labels: ✨기능추가

#19 [Client] 상세페이지 form 수정 / MyPage 레이아웃 제작중
  client/data/data.json
  client/src/App.jsx
  client/src/components/Items/FilterButtons.jsx
  client/src/components/Items/HeaertVoteButton.jsx
  client/src/components/Items/Item.jsx
  client/src/components/Items/MyReivewForms.jsx
  client/src/components/Items/ProductInformation.jsx
  client/src/components/Mypage/MyReviewBox.jsx
  client/src/components/Mypage/Profile.jsx
  client/src/pages/MyPage.jsx
Labels: ✨기능추가, 🌈레이아웃

#22 조합 디테일
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/assets/dummyImg.png
  client/src/components/MixFoodCard/index.jsx
  client/src/components/MixFoodCard/style.js
  client/src/pages/MixDetail.jsx
  client/src/pages/MixMain.jsx
Labels: 🌈레이아웃, 🧑‍💻Front

#26 MixList
  client/data/Mixdummydata.json
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/assets/ListdummyImg.png
  client/src/components/MixFoodCard/index.jsx
  client/src/components/MixFoodCard/style.js
  client/src/components/MixFoodCardList/index.jsx
  client/src/components/MixFoodCardList/style.js
  client/src/pages/MixCreate.jsx
  client/src/pages/MixDetail.jsx
  client/src/pages/MixList.jsx
  client/src/pages/MixMain.jsx
  client/src/util/convertor.jsx
Labels: ✨기능추가, 🌈레이아웃, 🧑‍💻Front

#23 feat: Mix,MixReply ProtoType 생성
  .idea/compiler.xml
  .idea/git_toolbox_prj.xml
  .idea/uiDesigner.xml
  server/.gitignore
  server/build.gradle
  server/src/main/java/server/beerfactory/BeerfactoryApplication.java
  server/src/main/java/server/beerfactory/controller/mix/MixController.java
  server/src/main/java/server/beerfactory/controller/mix/MixReplyController.java
  server/src/main/java/server/beerfactory/dto/mix/MixDto.java
  server/src/main/java/server/beerfactory/dto/mix/MixReplyDto.java
  server/src/main/java/server/beerfactory/entity/mix/Mix.java
  server/src/main/java/server/beerfactory/entity/mix/MixJoinTag.java
  server/src/main/java/server/beerfactory/entity/mix/MixReply.java
  server/src/main/java/server/beerfactory/entity/mix/MixTag.java
  server/src/main/java/server/beerfactory/exception/ExceptionCode.java
  server/src/main/java/server/beerfactory/mapper/mix/MixMapper.java
  server/src/main/java/server/beerfactory/mapper/mix/MixReplyMapper.java
  server/src/main/java/server/beerfactory/repository/mix/MixReplyRepository.java
  server/src/main/java/server/beerfactory/repository/mix/MixRepository.java
  server/src/main/java/server/beerfactory/service/mix/MixReplyService.java
  server/src/main/java/server/beerfactory/service/mix/MixService.java
Labels: ✨기능추가, 🏎리팩토링

#29 [Client] feat: 상세 페이지 구현(미완성)
  client/data/MixdummydataDetail.json
  client/src/components/MixDetailComponents/MixDetailReviewForms.jsx
  client/src/components/MixDetailComponents/index.jsx
  client/src/components/MixDetailComponents/style.js
  client/src/components/MixFoodCardList/index.jsx
  client/src/components/MixFoodCardList/style.js
  client/src/pages/MixCreate.jsx
  client/src/pages/MixDetail.jsx
  client/src/pages/MixList.jsx
  client/src/util/convertor.jsx
Labels: ✨기능추가, 🌈레이아웃, 🧑‍💻Front

#33 [Client]:sparkles: feat: 로그인/ 회원가입 레이아웃 구현, Beer request 레이아웃 구현
  client/src/App.jsx
  client/src/components/BeerReq/index.jsx
  client/src/components/BeerReq/style.js
  client/src/components/Error/style.js
  client/src/components/Footer/index.jsx
  client/src/components/Header-Bottom/index.jsx
  client/src/components/Layout/style.js
  client/src/components/Signin/index.jsx
  client/src/components/Signin/style.js
  client/src/components/Signup/index.jsx
  client/src/components/Signup/style.js
  client/src/constants/header_footer.js
  client/src/pages/BeerRequest.jsx
  client/src/pages/Join.jsx
  client/src/pages/Login.jsx
Labels: 🌈레이아웃, 🧑‍💻Front

#35 [Client]feat: MixCreate
  client/src/components/MixCreate/CameraButton.jsx
  client/src/components/MixCreate/ContentBox.jsx
  client/src/components/MixCreate/MixCreateBox.jsx
  client/src/components/MixCreate/SubmitButton.jsx
  client/src/components/MixCreate/TitleBox.jsx
  client/src/pages/MixCreate.jsx
Labels: ✨기능추가, 🌈레이아웃, 🧑‍💻Front

#44 Mix API 작업
  client/package-lock.json
  client/src/components/Loading/Loading.jsx
  client/src/components/MixDetailComponents/index.jsx
  client/src/components/MixDetailComponents/style.js
  client/src/components/MixFoodCardList/Pagination.jsx
  client/src/components/MixFoodCardList/index.jsx
  client/src/components/MixFoodCardList/style.js
  client/src/components/Modal/MixDetailDelete.jsx
  client/src/pages/MixList.jsx
  client/src/util/fetchMix.jsx
  client/src/util/fetchMixVote.jsx
  client/src/util/fetchReply.jsx
Labels: ✨기능추가, 🧑‍💻Front
